INSERT INTO produits(nom_produit, type_produit, marque, genre, prix) VALUES
('Jean slim bleu', 'pantalons', 'Levi''s', 'homme', 19.99),
('Jean boyfriend délavé', 'pantalons', 'Zara', 'femme', 14.99),
('Chino beige', 'pantalons', 'Gap', 'homme', 24.99),
('Pantalon taille haute noir', 'pantalons', 'H&M', 'femme', 29.99),
('Chemise en lin blanc', 'chemises', 'Uniqlo', 'homme', 39.99),
('Chemise en jean bleu', 'chemises', 'Levi''s', 'femme', 49.99),
('Chemise à rayures fines', 'chemises', 'Ralph Lauren', 'homme', 79.99),
('Chemisier en soie noir', 'chemises', 'Sandro', 'femme', 129.99),
('Veste en laine camel', 'vestes', 'Mango', 'homme', 89.99),
('Veste en cuir noir', 'vestes', 'The Kooples', 'femme', 259.99),
('Veste en jean délavé', 'vestes', 'Zara', 'homme', 49.99),
('Veste en laine bouclée beige', 'vestes', 'Sandro', 'femme', 199.99),
('Pull en laine col roulé gris', 'pulls', 'H&M', 'homme', 29.99),
('Pull en cachemire rose poudré', 'pulls', 'Uniqlo', 'femme', 129.99),
('Pull à motifs géométriques', 'pulls', 'Zara', 'homme', 39.99),
('Pull en laine à col V', 'pulls', 'Mango', 'femme', 59.99),
('Short en jean déchiré', 'shorts', 'Levi''s', 'homme', 29.99),
('Short en lin beige', 'shorts', 'H&M', 'femme', 14.99),
('Short en jean taille haute', 'shorts', 'Zara', 'femme', 19.99),
('Chaussettes hautes en laine', 'chaussettes', 'Falke', 'homme', 14.99),
('Chaussettes en coton coloré', 'chaussettes', 'Happy Socks', 'femme', 9.99),
('Robe en coton imprimé', 'robes', 'Sandro', 'femme', 149.99),
('Costume complet gris', 'costumes', 'Hugo Boss', 'homme', 499.99),
('Blazer en laine marine', 'vestes', 'Ralph Lauren', 'homme', 349.99),
('Manteau en laine beige', 'manteaux', 'Sandro', 'femme', 299.99),
('Parka kaki avec fausse fourrure', 'manteaux', 'Zara', 'homme', 129.99),
('Blouson en cuir marron', 'vestes', 'The Kooples', 'homme', 399.99),
('Jean slim noir', 'pantalons', 'Diesel', 'homme', 59.99),
('Jean coupe droite', 'pantalons', 'Tommy Hilfiger', 'femme', 69.99),
('Chino vert', 'pantalons', 'Lacoste', 'homme', 79.99),
('Pantalon taille haute blanc', 'pantalons', 'Calvin Klein', 'femme', 89.99),
('Chemise en lin rayé', 'chemises', 'Armani', 'homme', 99.99),
('Chemise en jean noir', 'chemises', 'Gucci', 'femme', 159.99),
('Chemise à carreaux', 'chemises', 'Burberry', 'homme', 129.99),
('Chemisier en soie blanc', 'chemises', 'Chloé', 'femme', 249.99),
('Veste en laine bleu marine', 'vestes', 'Balenciaga', 'homme', 399.99),
('Veste en cuir rouge', 'vestes', 'Saint Laurent', 'femme', 599.99),
('Veste en jean brut', 'vestes', 'Dolce & Gabbana', 'homme', 299.99),
('Veste en laine bouclée noir', 'vestes', 'Prada', 'femme', 699.99),
('Pull en laine col roulé noir', 'pulls', 'Versace', 'homme', 179.99),
('Pantalon cargo kaki', 'pantalons', 'Timberland', 'homme', 64.99),
('Legging noir', 'pantalons', 'Adidas', 'femme', 34.99),
('Chino rouge', 'pantalons', 'Fred Perry', 'homme', 84.99),
('Pantalon taille haute rayé', 'pantalons', 'Ted Baker', 'femme', 104.99),
('Chemise en popeline blanche', 'chemises', 'Paul Smith', 'homme', 119.99),
('Chemise en soie verte', 'chemises', 'Givenchy', 'femme', 259.99),
('Chemise à pois', 'chemises', 'Kenzo', 'homme', 139.99),
('Chemisier en dentelle rose', 'chemises', 'Miu Miu', 'femme', 349.99),
('Veste en laine grise', 'vestes', 'Alexander McQueen', 'homme', 499.99),
('Veste en daim beige', 'vestes', 'Loewe', 'femme', 799.99),
('Veste en jean noir', 'vestes', 'Valentino', 'homme', 399.99),
('Veste en velours bordeaux', 'vestes', 'Fendi', 'femme', 899.99),
('Pull en laine col roulé bleu', 'pulls', 'Roberto Cavalli', 'homme', 189.99),
('Pull en cachemire rouge', 'pulls', 'Stella McCartney', 'femme', 219.99),
('Short cargo', 'shorts', 'Carhartt', 'homme', 49.99);

INSERT INTO accessoires(nom_accessoire, type_accessoire, type_produit) VALUES
('Ceinture en cuir', 'Ceinture', 'pantalons'),
('Bretelles fines', 'Bretelles', 'pantalons'),
('Bretelles larges', 'Bretelles', 'pantalons'),
('Cravate slim', 'Cravate', 'chemises'),
('Cravate classique', 'Cravate', 'chemises'),
('Nœud papillon', 'Nœud papillon', 'chemises'),
('Pochette de costume', 'Pochette', 'chemises'),
('Ceinture en tissu', 'Ceinture', 'pantalons'),
('Écharpe en laine', 'Écharpe', 'vestes'),
('Bonnet en laine', 'Bonnet', 'vestes'),
('Collier', 'Collier', 'chemises'),
('Bracelet', 'Bracelet', 'chemises'),
('Ceinture tressée', 'Ceinture', 'pantalons'),
('Bretelles à motifs', 'Bretelles', 'pantalons'),
('Cravate large', 'Cravate', 'chemises'),
('Foulard en soie', 'Foulard', 'chemises'),
('Ceinture en métal', 'Ceinture', 'pantalons'),
('Écharpe en soie', 'Écharpe', 'vestes'),
('Bonnet en cachemire', 'Bonnet', 'vestes');

INSERT INTO dispo_tailles(id_produit, taille, quantite) VALUES
(1, 'XS', 4),
(1, 'XXL', 2),
(2, 'L', 4),
(2, 'XL', 3),
(2, 'XXL', 3),
(6, 'S', 3),
(6, 'M', 2),
(6, 'L', 2),
(6, 'XL', 1),
(12, 'XS', 2),
(12, 'M', 4),
(12, 'XL', 3),
(12, 'XXL', 1),
(28, 'S', 4),
(28, 'M', 4),
(28, 'L', 4),
(28, 'XL', 2),
(31, 'XS', 2),
(31, 'S', 3),
(31, 'M', 4),
(31, 'L', 3),
(31, 'XL', 2),
(42, 'S', 3),
(42, 'M', 4),
(42, 'L', 4),
(42, 'XL', 2),
(45, 'XS', 1),
(45, 'S', 3),
(45, 'M', 4),
(45, 'L', 3),
(45, 'XL', 2),
(3, 'M', 3),
(3, 'L', 4),
(4, 'S', 3),
(4, 'M', 4),
(7, 'L', 3),
(7, 'XL', 1),
(8, 'XS', 2),
(8, 'S', 4),
(13, 'M', 4),
(13, 'L', 4),
(14, 'XS', 1),
(14, 'S', 3),
(19, 'M', 3),
(19, 'L', 3),
(20, 'S', 3),
(20, 'M', 4),
(25, 'L', 4),
(25, 'XL', 2),
(26, 'S', 3),
(9, 'M', 1),
(9, 'L', 1),
(11, 'S', 1),
(26, 'M', 2),
(32, 'M', 1),
(32, 'L', 1),
(33, 'S', 1),
(33, 'M', 2),
(5, 'M', 1),
(5, 'L', 1);

INSERT INTO produits_accessoires (id_produit, id_accessoire) VALUES
(1, 1),
(3, 3),
(28, 8),
(29, 9),
(30, 10),
(31, 11),
(42, 12),
(43, 13),
(44, 14),
(45, 15),
(46,16),
(33, 6),
(35, 10),
(47, 11);

INSERT INTO combinaisons (type,prix) VALUES
('Combinaison de base',40),
('Combinaison de base',40),
('Combinaison business',100),
('Combinaison de luxe',200),
('Combinaison de luxe',200);

INSERT INTO combinaisons_parts (id_combi, id_produit) VALUES
-- Combinaisons de base
(1,4),
(1,32),
(1,9),
(2,41),
(2,33),
(2,11),

-- Combinaison business
(3,30),
(3,33),
(3,12),

-- Combinaisons luxe
(4,31),
(4,35),
(4,47),
(5,43),
(5,45),
(5,46);


INSERT INTO gerants(login,mdp) VALUES('admin',sha256('admin'));
INSERT INTO clients(nom,prenom,tel,email,adresse,adresse2,ville,code,login,mdp) VALUES('RODRIGUEZ','Lucas','0102030405','lucas@gmail.com','1 rue des pigeons','','Paris','75017','lucasrdz',sha256('lucas'));